name: Lib CI Tag Deployment (Release)

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
      - '!*.*.*-**'
jobs:
  build:
    name: Build Lib

    runs-on: ubuntu-latest

    env:
      GITHUB_USER: ${{ secrets.GH_USER }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
      MAVEN_CENTRAL_PASS: ${{ secrets.MAVEN_CENTRAL_PASS }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release AAR
        run: ./gradlew :pin_lock_compose:assembleRelease --info

      - name: Get aar path
        id: aar-path
        run: echo "path=$(find . -regex '^.*/build/outputs/aar/.*\.aar$' -type f | head -1)" >> $GITHUB_OUTPUT

      - name: Create Release with Fastlane changelogs notes
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workspace }}/changelogs/${{ github.ref_name }}.txt
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          make_latest: true
          draft: false
          prerelease: false
          files: ${{ github.workspace }}/${{ steps.aar-path.outputs.path }}